// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apigen

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateAvatarUploadUrlRequestContentType.
const (
	Imagejpeg CreateAvatarUploadUrlRequestContentType = "image/jpeg"
	Imagepng  CreateAvatarUploadUrlRequestContentType = "image/png"
	Imagewebp CreateAvatarUploadUrlRequestContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the CreateAvatarUploadUrlRequestContentType enum.
func (e CreateAvatarUploadUrlRequestContentType) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// ArchiveRequest アーカイブ状態(ユーザーごと)。true でアーカイブ、false で解除。
type ArchiveRequest struct {
	ArchiveFlg bool `json:"archive_flg"`
}

// AvatarUploadUrlResponse アップロード先の署名付き URL。この URL へ画像本体を PUT する(Content-Type ヘッダは要求時と同じ値にする)。
type AvatarUploadUrlResponse struct {
	// Key アップロード後、確定(PUT /api/user_info/avatar/)に渡すオブジェクトキー。
	Key       string `json:"key"`
	UploadUrl string `json:"upload_url"`
}

// ChangeEmailRequest メールアドレス変更。本人確認のため現在のパスワードを要求する。
type ChangeEmailRequest struct {
	Email    string `json:"email" validate:"required,email,max=50"`
	Password string `json:"password" validate:"required"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password" validate:"required"`
	NewPassword     string `json:"new_password" validate:"required,min=8"`
}

// ConfirmAvatarRequest defines model for ConfirmAvatarRequest.
type ConfirmAvatarRequest struct {
	Key string `json:"key" validate:"required"`
}

// CookingInput defines model for CookingInput.
type CookingInput struct {
	Ingredients NameInput `json:"ingredients"`
	Quantity    float64   `json:"quantity"`
	Unit        string    `json:"unit"`
}

// CookingResponse defines model for CookingResponse.
type CookingResponse struct {
	Ingredients NameResponse `json:"ingredients"`
	Quantity    float64      `json:"quantity"`
	Unit        string       `json:"unit"`
}

// CreateAvatarUploadUrlRequest defines model for CreateAvatarUploadUrlRequest.
type CreateAvatarUploadUrlRequest struct {
	ContentType CreateAvatarUploadUrlRequestContentType `json:"content_type" validate:"required,oneof=image/jpeg image/png image/webp"`
}

// CreateAvatarUploadUrlRequestContentType defines model for CreateAvatarUploadUrlRequest.ContentType.
type CreateAvatarUploadUrlRequestContentType string

// Error Echo の既定エラー形式
type Error struct {
	Message string `json:"message"`
}

// LabelInput defines model for LabelInput.
type LabelInput struct {
	Name string `json:"name" validate:"required"`
}

// LabelItem ユーザーが管理するラベル(マスタ)。作成・改名・削除の対象。
type LabelItem struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// LabelResponse defines model for LabelResponse.
type LabelResponse struct {
	Name string `json:"name"`
}

// NameInput defines model for NameInput.
type NameInput struct {
	Name string `json:"name" validate:"required"`
}

// NameResponse defines model for NameResponse.
type NameResponse struct {
	Name string `json:"name"`
}

// OgpResponse defines model for OgpResponse.
type OgpResponse struct {
	// Image og:image の URL。取得できなければ空文字。
	Image string `json:"image"`

	// Title og:title。取得できなければ空文字。
	Title string `json:"title"`
}

// RecipeRequest defines model for RecipeRequest.
type RecipeRequest struct {
	Cooking []CookingInput `json:"cooking,omitempty"`

	// CreateFor 何人前。未指定時はサーバ側で 1 に正規化される。
	CreateFor int `json:"create_for,omitempty"`

	// CreateTime 調理時間(分)。任意。
	CreateTime *int              `json:"create_time,omitempty"`
	Label      []LabelInput      `json:"label,omitempty"`
	Procedure  string            `json:"procedure,omitempty"`
	Season     []SeasonInput     `json:"season,omitempty"`
	SharedUser []SharedUserInput `json:"shared_user,omitempty"`

	// SourceUrl 参考にした外部レシピの URL。任意。空文字で未設定。
	SourceUrl string `json:"source_url,omitempty"`

	// ThumbnailUrl source_url の OGP 画像 URL(サムネイル)。任意。空文字で未設定。
	ThumbnailUrl string `json:"thumbnail_url,omitempty"`
	Title        string `json:"title" validate:"required"`
}

// RecipeResponse defines model for RecipeResponse.
type RecipeResponse struct {
	ArchiveFlg bool              `json:"archive_flg"`
	Cooking    []CookingResponse `json:"cooking"`
	CreateFor  int               `json:"create_for"`

	// CreateTime 調理時間(分)。任意。null 可。
	CreateTime *int `json:"create_time"`

	// CreatedAt JST。形式: YYYY-MM-DD HH:mm
	CreatedAt  string           `json:"created_at"`
	ID         string           `json:"id"`
	Label      []LabelResponse  `json:"label"`
	Owner      UserListItem     `json:"owner"`
	Procedure  string           `json:"procedure"`
	Season     []SeasonResponse `json:"season"`
	SharedUser []UserListItem   `json:"shared_user"`

	// SourceUrl 参考にした外部レシピの URL。未設定時は空文字。
	SourceUrl string `json:"source_url"`

	// ThumbnailUrl source_url の OGP 画像 URL(サムネイル)。未設定時は空文字。
	ThumbnailUrl string `json:"thumbnail_url"`
	Title        string `json:"title"`

	// UpdatedAt JST。形式: YYYY-MM-DD HH:mm
	UpdatedAt string `json:"updated_at"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	Access string `json:"access"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email,max=50"`
	Password string `json:"password" validate:"required,min=8"`
	Username string `json:"username" validate:"required,max=50"`
}

// ReorderRequest 表示したい順にレシピ ID を並べた配列(先頭 = 一番上)
type ReorderRequest struct {
	RecipeIds []string `json:"recipe_ids" validate:"required,dive,uuid"`
}

// SeasonInput defines model for SeasonInput.
type SeasonInput struct {
	Quantity  float64   `json:"quantity"`
	Seasoning NameInput `json:"seasoning"`
	Unit      string    `json:"unit"`
}

// SeasonResponse defines model for SeasonResponse.
type SeasonResponse struct {
	Quantity  float64      `json:"quantity"`
	Seasoning NameResponse `json:"seasoning"`
	Unit      string       `json:"unit"`
}

// SharedUserInput defines model for SharedUserInput.
type SharedUserInput struct {
	Username string `json:"username" validate:"required"`
}

// ShoppingListItemInput defines model for ShoppingListItemInput.
type ShoppingListItemInput struct {
	Name string `json:"name" validate:"required,max=50"`
}

// ShoppingListItemResponse defines model for ShoppingListItemResponse.
type ShoppingListItemResponse struct {
	Checked bool   `json:"checked"`
	ID      string `json:"id"`
	Name    string `json:"name"`
}

// ShoppingListItemUpdateRequest 項目のチェック状態。true でチェック済み、false で未チェック。
type ShoppingListItemUpdateRequest struct {
	Checked bool `json:"checked"`
}

// ShoppingListReorderRequest 表示したい順に項目 ID を並べた配列(先頭 = 一番上)
type ShoppingListReorderRequest struct {
	ItemIds []string `json:"item_ids" validate:"required,dive,uuid"`
}

// ShoppingListResponse 買い物リスト。項目はチェック済みが末尾、同グループ内は追加順。
type ShoppingListResponse struct {
	ID         string                     `json:"id"`
	Items      []ShoppingListItemResponse `json:"items"`
	Owner      UserListItem               `json:"owner"`
	SharedUser []UserListItem             `json:"shared_user"`
}

// ShoppingListSharesRequest defines model for ShoppingListSharesRequest.
type ShoppingListSharesRequest struct {
	SharedUser []SharedUserInput `json:"shared_user"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

// TokenResponse refresh は body に含めず Cookie で発行する
type TokenResponse struct {
	Access string `json:"access"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Username string `json:"username" validate:"required,max=50"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	// AvatarUrl プロフィール画像の URL。未設定なら null。
	AvatarUrl *string `json:"avatar_url"`

	// CreatedAt 登録日時(JST, "YYYY-MM-DD HH:MM")
	CreatedAt string `json:"created_at"`
	Email     string `json:"email"`
	ID        string `json:"id"`
	Username  string `json:"username"`
}

// UserListItem defines model for UserListItem.
type UserListItem struct {
	// AvatarUrl プロフィール画像の URL。未設定なら null。
	AvatarUrl *string `json:"avatar_url"`
	ID        string  `json:"id"`
	Username  string  `json:"username"`
}

// BadRequest Echo の既定エラー形式
type BadRequest = Error

// Conflict Echo の既定エラー形式
type Conflict = Error

// Forbidden Echo の既定エラー形式
type Forbidden = Error

// NotFound Echo の既定エラー形式
type NotFound = Error

// Unauthorized Echo の既定エラー形式
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// FetchOgpParams defines parameters for FetchOgp.
type FetchOgpParams struct {
	// Url OGP を取得する対象の URL
	Url string `form:"url" json:"url"`
}

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = LabelInput

// UpdateLabelJSONRequestBody defines body for UpdateLabel for application/json ContentType.
type UpdateLabelJSONRequestBody = LabelInput

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = RecipeRequest

// ReorderRecipesJSONRequestBody defines body for ReorderRecipes for application/json ContentType.
type ReorderRecipesJSONRequestBody = ReorderRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = RecipeRequest

// ArchiveRecipeJSONRequestBody defines body for ArchiveRecipe for application/json ContentType.
type ArchiveRecipeJSONRequestBody = ArchiveRequest

// AddShoppingListItemJSONRequestBody defines body for AddShoppingListItem for application/json ContentType.
type AddShoppingListItemJSONRequestBody = ShoppingListItemInput

// ReorderShoppingListItemsJSONRequestBody defines body for ReorderShoppingListItems for application/json ContentType.
type ReorderShoppingListItemsJSONRequestBody = ShoppingListReorderRequest

// UpdateShoppingListItemJSONRequestBody defines body for UpdateShoppingListItem for application/json ContentType.
type UpdateShoppingListItemJSONRequestBody = ShoppingListItemUpdateRequest

// UpdateShoppingListSharesJSONRequestBody defines body for UpdateShoppingListShares for application/json ContentType.
type UpdateShoppingListSharesJSONRequestBody = ShoppingListSharesRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = TokenRequest

// UpdateUserInfoJSONRequestBody defines body for UpdateUserInfo for application/json ContentType.
type UpdateUserInfoJSONRequestBody = UpdateUserRequest

// CreateAvatarUploadUrlJSONRequestBody defines body for CreateAvatarUploadUrl for application/json ContentType.
type CreateAvatarUploadUrlJSONRequestBody = CreateAvatarUploadUrlRequest

// ConfirmAvatarJSONRequestBody defines body for ConfirmAvatar for application/json ContentType.
type ConfirmAvatarJSONRequestBody = ConfirmAvatarRequest

// ChangeEmailJSONRequestBody defines body for ChangeEmail for application/json ContentType.
type ChangeEmailJSONRequestBody = ChangeEmailRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest
