// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apigen

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// CookingInput defines model for CookingInput.
type CookingInput struct {
	Ingredients NameInput `json:"ingredients"`
	Quantity    int       `json:"quantity"`
	Unit        string    `json:"unit"`
}

// CookingResponse defines model for CookingResponse.
type CookingResponse struct {
	Ingredients NameResponse `json:"ingredients"`
	Quantity    int          `json:"quantity"`
	Unit        string       `json:"unit"`
}

// Error Echo の既定エラー形式 (api ADR-0003)
type Error struct {
	Message string `json:"message"`
}

// LabelInput defines model for LabelInput.
type LabelInput struct {
	Name string `json:"name" validate:"required"`
}

// LabelResponse defines model for LabelResponse.
type LabelResponse struct {
	Name string `json:"name"`
}

// NameInput defines model for NameInput.
type NameInput struct {
	Name string `json:"name" validate:"required"`
}

// NameResponse defines model for NameResponse.
type NameResponse struct {
	Name string `json:"name"`
}

// RecipeRequest defines model for RecipeRequest.
type RecipeRequest struct {
	ArchiveFlg bool           `json:"archive_flg,omitempty"`
	Cooking    []CookingInput `json:"cooking,omitempty"`

	// CreateFor 何人前。未指定時はサーバ側で 1 に正規化される。
	CreateFor int `json:"create_for,omitempty"`

	// CreateTime 調理時間(分)。任意。
	CreateTime *int              `json:"create_time,omitempty"`
	Label      []LabelInput      `json:"label,omitempty"`
	Procedure  string            `json:"procedure,omitempty"`
	Season     []SeasonInput     `json:"season,omitempty"`
	SharedUser []SharedUserInput `json:"shared_user,omitempty"`
	Title      string            `json:"title" validate:"required"`
}

// RecipeResponse defines model for RecipeResponse.
type RecipeResponse struct {
	ArchiveFlg bool              `json:"archive_flg"`
	Cooking    []CookingResponse `json:"cooking"`
	CreateFor  int               `json:"create_for"`

	// CreateTime 調理時間(分)。任意。null 可。
	CreateTime *int `json:"create_time"`

	// CreatedAt JST。形式: YYYY-MM-DD HH:mm
	CreatedAt  string           `json:"created_at"`
	ID         uint             `json:"id"`
	Label      []LabelResponse  `json:"label"`
	Owner      UserListItem     `json:"owner"`
	Procedure  string           `json:"procedure"`
	Season     []SeasonResponse `json:"season"`
	SharedUser []UserListItem   `json:"shared_user"`
	Title      string           `json:"title"`

	// UpdatedAt JST。形式: YYYY-MM-DD HH:mm
	UpdatedAt string `json:"updated_at"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	Access string `json:"access"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email,max=50"`
	Password string `json:"password" validate:"required,min=8"`
	Username string `json:"username" validate:"required,max=50"`
}

// SeasonInput defines model for SeasonInput.
type SeasonInput struct {
	Quantity  int       `json:"quantity"`
	Seasoning NameInput `json:"seasoning"`
	Unit      string    `json:"unit"`
}

// SeasonResponse defines model for SeasonResponse.
type SeasonResponse struct {
	Quantity  int          `json:"quantity"`
	Seasoning NameResponse `json:"seasoning"`
	Unit      string       `json:"unit"`
}

// SharedUserInput defines model for SharedUserInput.
type SharedUserInput struct {
	Username string `json:"username" validate:"required"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Password string `json:"password" validate:"required"`
	Username string `json:"username" validate:"required"`
}

// TokenResponse refresh は body に含めず Cookie で発行する (api ADR-0004)
type TokenResponse struct {
	Access string `json:"access"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	Email    string `json:"email"`
	ID       uint   `json:"id"`
	Username string `json:"username"`
}

// UserListItem defines model for UserListItem.
type UserListItem struct {
	ID       uint   `json:"id"`
	Username string `json:"username"`
}

// BadRequest Echo の既定エラー形式 (api ADR-0003)
type BadRequest = Error

// Conflict Echo の既定エラー形式 (api ADR-0003)
type Conflict = Error

// Forbidden Echo の既定エラー形式 (api ADR-0003)
type Forbidden = Error

// NotFound Echo の既定エラー形式 (api ADR-0003)
type NotFound = Error

// Unauthorized Echo の既定エラー形式 (api ADR-0003)
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = RecipeRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = RecipeRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = TokenRequest
