// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apigen

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// CookingInput defines model for CookingInput.
type CookingInput struct {
	Ingredients NameInput `json:"ingredients"`
	Quantity    int       `json:"quantity"`
	Unit        string    `json:"unit"`
}

// CookingResponse defines model for CookingResponse.
type CookingResponse struct {
	Ingredients NamedRef `json:"ingredients"`
	Quantity    int      `json:"quantity"`
	Unit        string   `json:"unit"`
}

// Error Echo の既定エラー形式 (api ADR-0003)
type Error struct {
	Message string `json:"message"`
}

// LabelInput defines model for LabelInput.
type LabelInput struct {
	Name string `json:"name"`
}

// LabelResponse defines model for LabelResponse.
type LabelResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// NameInput defines model for NameInput.
type NameInput struct {
	Name string `json:"name"`
}

// NamedRef defines model for NamedRef.
type NamedRef struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// RecipeRequest defines model for RecipeRequest.
type RecipeRequest struct {
	ArchiveFlg *bool           `json:"archive_flg,omitempty"`
	Cooking    *[]CookingInput `json:"cooking,omitempty"`

	// CreateFor 何人前。未指定時はサーバ側で 1 に正規化される。
	CreateFor *int `json:"create_for,omitempty"`

	// CreateTime 調理時間(分)。任意。
	CreateTime *int               `json:"create_time,omitempty"`
	Label      *[]LabelInput      `json:"label,omitempty"`
	Procedure  *string            `json:"procedure,omitempty"`
	Season     *[]SeasonInput     `json:"season,omitempty"`
	SharedUser *[]SharedUserInput `json:"shared_user,omitempty"`
	Title      string             `json:"title"`
}

// RecipeResponse defines model for RecipeResponse.
type RecipeResponse struct {
	ArchiveFlg bool              `json:"archive_flg"`
	Cooking    []CookingResponse `json:"cooking"`
	CreateFor  int               `json:"create_for"`

	// CreateTime 調理時間(分)。任意。
	CreateTime *int `json:"create_time,omitempty"`

	// CreatedAt JST。形式: YYYY-MM-DD HH:mm
	CreatedAt  string           `json:"created_at"`
	Id         int64            `json:"id"`
	Label      []LabelResponse  `json:"label"`
	Owner      UserListItem     `json:"owner"`
	Procedure  string           `json:"procedure"`
	Season     []SeasonResponse `json:"season"`
	SharedUser []UserListItem   `json:"shared_user"`
	Title      string           `json:"title"`

	// UpdatedAt JST。形式: YYYY-MM-DD HH:mm
	UpdatedAt string `json:"updated_at"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	Refresh string `json:"refresh"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	Access string `json:"access"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// SeasonInput defines model for SeasonInput.
type SeasonInput struct {
	Quantity  int       `json:"quantity"`
	Seasoning NameInput `json:"seasoning"`
	Unit      string    `json:"unit"`
}

// SeasonResponse defines model for SeasonResponse.
type SeasonResponse struct {
	Quantity  int      `json:"quantity"`
	Seasoning NamedRef `json:"seasoning"`
	Unit      string   `json:"unit"`
}

// SharedUserInput defines model for SharedUserInput.
type SharedUserInput struct {
	Username string `json:"username"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	Access  string `json:"access"`
	Refresh string `json:"refresh"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	Email    string `json:"email"`
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

// UserListItem defines model for UserListItem.
type UserListItem struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

// BadRequest Echo の既定エラー形式 (api ADR-0003)
type BadRequest = Error

// Conflict Echo の既定エラー形式 (api ADR-0003)
type Conflict = Error

// Forbidden Echo の既定エラー形式 (api ADR-0003)
type Forbidden = Error

// NotFound Echo の既定エラー形式 (api ADR-0003)
type NotFound = Error

// Unauthorized Echo の既定エラー形式 (api ADR-0003)
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateRecipeJSONRequestBody defines body for CreateRecipe for application/json ContentType.
type CreateRecipeJSONRequestBody = RecipeRequest

// UpdateRecipeJSONRequestBody defines body for UpdateRecipe for application/json ContentType.
type UpdateRecipeJSONRequestBody = RecipeRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = TokenRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest
